import os

def w(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w', encoding='utf-8').write(content)
    print('Written:', path)

base = 'e:/Society_Managment/frontend/lib/features'

staff_screen = (
    "import 'package:flutter/material.dart';\n"
    "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
    "import '../../../core/theme/app_colors.dart';\n"
    "import '../../../core/theme/app_text_styles.dart';\n"
    "import '../providers/staff_provider.dart';\n\n"
    "class StaffScreen extends ConsumerWidget {\n"
    "  const StaffScreen({super.key});\n\n"
    "  @override\n"
    "  Widget build(BuildContext context, WidgetRef ref) {\n"
    "    final async = ref.watch(staffProvider);\n"
    "    return Scaffold(\n"
    "      backgroundColor: AppColors.background,\n"
    "      appBar: AppBar(backgroundColor: AppColors.surface, elevation: 0,\n"
    "          title: Text('Staff', style: AppTextStyles.titleLarge)),\n"
    "      floatingActionButton: FloatingActionButton.extended(\n"
    "        onPressed: () {},\n"
    "        backgroundColor: AppColors.primary,\n"
    "        icon: const Icon(Icons.person_add_rounded, color: Colors.white),\n"
    "        label: Text('Add Staff', style: AppTextStyles.buttonSmall),\n"
    "      ),\n"
    "      body: async.when(\n"
    "        loading: () => const Center(child: CircularProgressIndicator()),\n"
    "        error: (e, _) => Center(child: Text('Error loading staff')),\n"
    "        data: (staff) => ListView.builder(\n"
    "          padding: const EdgeInsets.all(16),\n"
    "          itemCount: staff.length,\n"
    "          itemBuilder: (ctx, i) {\n"
    "            final s = staff[i];\n"
    "            final present = s['status'] == 'present';\n"
    "            return Card(\n"
    "              elevation: 0,\n"
    "              margin: const EdgeInsets.only(bottom: 10),\n"
    "              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12),\n"
    "                  side: const BorderSide(color: Color(0xFFE2E8F0))),\n"
    "              child: ListTile(\n"
    "                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),\n"
    "                leading: CircleAvatar(\n"
    "                  backgroundColor: AppColors.primary.withValues(alpha: 0.1),\n"
    "                  child: Text((s['name'] as String)[0],\n"
    "                      style: AppTextStyles.body1.copyWith(color: AppColors.primary, fontWeight: FontWeight.w700)),\n"
    "                ),\n"
    "                title: Text(s['name'] as String, style: AppTextStyles.body1),\n"
    "                subtitle: Text('${s[\"role\"]} | Shift: ${s[\"shift\"]}', style: AppTextStyles.bodySmall),\n"
    "                trailing: Container(\n"
    "                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),\n"
    "                  decoration: BoxDecoration(\n"
    "                    color: present ? AppColors.secondary.withValues(alpha: 0.1) : AppColors.error.withValues(alpha: 0.1),\n"
    "                    borderRadius: BorderRadius.circular(20),\n"
    "                  ),\n"
    "                  child: Text(s['status'] as String,\n"
    "                      style: AppTextStyles.labelMedium.copyWith(color: present ? AppColors.secondary : AppColors.error)),\n"
    "                ),\n"
    "              ),\n"
    "            );\n"
    "          },\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

gate_pass_screen = (
    "import 'package:flutter/material.dart';\n"
    "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
    "import '../../../core/theme/app_colors.dart';\n"
    "import '../../../core/theme/app_text_styles.dart';\n"
    "import '../providers/gate_pass_provider.dart';\n\n"
    "class GatePassScreen extends ConsumerWidget {\n"
    "  const GatePassScreen({super.key});\n\n"
    "  @override\n"
    "  Widget build(BuildContext context, WidgetRef ref) {\n"
    "    final async = ref.watch(gatePassProvider);\n"
    "    return Scaffold(\n"
    "      backgroundColor: AppColors.background,\n"
    "      appBar: AppBar(backgroundColor: AppColors.surface, elevation: 0,\n"
    "          title: Text('Gate Passes', style: AppTextStyles.titleLarge),\n"
    "          actions: [IconButton(icon: const Icon(Icons.qr_code_scanner_rounded), onPressed: () {})]),\n"
    "      floatingActionButton: FloatingActionButton.extended(\n"
    "        onPressed: () {},\n"
    "        backgroundColor: AppColors.primary,\n"
    "        icon: const Icon(Icons.add_rounded, color: Colors.white),\n"
    "        label: Text('Generate Pass', style: AppTextStyles.buttonSmall),\n"
    "      ),\n"
    "      body: async.when(\n"
    "        loading: () => const Center(child: CircularProgressIndicator()),\n"
    "        error: (e, _) => Center(child: Text('Error loading passes')),\n"
    "        data: (passes) => ListView.builder(\n"
    "          padding: const EdgeInsets.all(16),\n"
    "          itemCount: passes.length,\n"
    "          itemBuilder: (ctx, i) {\n"
    "            final p = passes[i];\n"
    "            final color = p['status'] == 'active' ? AppColors.secondary\n"
    "                : p['status'] == 'used' ? AppColors.textMuted : AppColors.error;\n"
    "            return Card(\n"
    "              elevation: 0,\n"
    "              margin: const EdgeInsets.only(bottom: 10),\n"
    "              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12),\n"
    "                  side: const BorderSide(color: Color(0xFFE2E8F0))),\n"
    "              child: ListTile(\n"
    "                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),\n"
    "                leading: Container(width: 40, height: 40,\n"
    "                  decoration: BoxDecoration(color: AppColors.primary.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),\n"
    "                  child: const Icon(Icons.badge_rounded, color: AppColors.primary)),\n"
    "                title: Text(p['visitor'] as String, style: AppTextStyles.body1),\n"
    "                subtitle: Text('Unit ${p[\"unit\"]} | Valid till ${p[\"validTill\"]}', style: AppTextStyles.bodySmall),\n"
    "                trailing: Container(\n"
    "                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),\n"
    "                  decoration: BoxDecoration(color: color.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(20)),\n"
    "                  child: Text(p['status'] as String, style: AppTextStyles.labelMedium.copyWith(color: color)),\n"
    "                ),\n"
    "              ),\n"
    "            );\n"
    "          },\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

domestic_screen = (
    "import 'package:flutter/material.dart';\n"
    "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
    "import '../../../core/theme/app_colors.dart';\n"
    "import '../../../core/theme/app_text_styles.dart';\n"
    "import '../providers/domestic_help_provider.dart';\n\n"
    "class DomesticHelpScreen extends ConsumerWidget {\n"
    "  const DomesticHelpScreen({super.key});\n\n"
    "  @override\n"
    "  Widget build(BuildContext context, WidgetRef ref) {\n"
    "    final async = ref.watch(domesticHelpProvider);\n"
    "    return Scaffold(\n"
    "      backgroundColor: AppColors.background,\n"
    "      appBar: AppBar(backgroundColor: AppColors.surface, elevation: 0,\n"
    "          title: Text('Domestic Help', style: AppTextStyles.titleLarge)),\n"
    "      floatingActionButton: FloatingActionButton.extended(\n"
    "        onPressed: () {},\n"
    "        backgroundColor: AppColors.primary,\n"
    "        icon: const Icon(Icons.person_add_rounded, color: Colors.white),\n"
    "        label: Text('Add Helper', style: AppTextStyles.buttonSmall),\n"
    "      ),\n"
    "      body: async.when(\n"
    "        loading: () => const Center(child: CircularProgressIndicator()),\n"
    "        error: (e, _) => Center(child: Text('Error')),\n"
    "        data: (helpers) => ListView.builder(\n"
    "          padding: const EdgeInsets.all(16),\n"
    "          itemCount: helpers.length,\n"
    "          itemBuilder: (ctx, i) {\n"
    "            final h = helpers[i];\n"
    "            final isActive = h['status'] == 'active';\n"
    "            return Card(\n"
    "              elevation: 0,\n"
    "              margin: const EdgeInsets.only(bottom: 10),\n"
    "              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12),\n"
    "                  side: const BorderSide(color: Color(0xFFE2E8F0))),\n"
    "              child: ListTile(\n"
    "                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),\n"
    "                leading: CircleAvatar(\n"
    "                  backgroundColor: AppColors.secondary.withValues(alpha: 0.1),\n"
    "                  child: const Icon(Icons.cleaning_services_rounded, color: AppColors.secondary, size: 20)),\n"
    "                title: Text(h['name'] as String, style: AppTextStyles.body1),\n"
    "                subtitle: Text('${h[\"type\"]} | Unit ${h[\"unit\"]}', style: AppTextStyles.bodySmall),\n"
    "                trailing: Container(\n"
    "                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),\n"
    "                  decoration: BoxDecoration(\n"
    "                    color: isActive ? AppColors.secondary.withValues(alpha: 0.1) : AppColors.error.withValues(alpha: 0.1),\n"
    "                    borderRadius: BorderRadius.circular(20),\n"
    "                  ),\n"
    "                  child: Text(h['status'] as String,\n"
    "                      style: AppTextStyles.labelMedium.copyWith(color: isActive ? AppColors.secondary : AppColors.error)),\n"
    "                ),\n"
    "              ),\n"
    "            );\n"
    "          },\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

delivery_screen = (
    "import 'package:flutter/material.dart';\n"
    "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
    "import '../../../core/theme/app_colors.dart';\n"
    "import '../../../core/theme/app_text_styles.dart';\n"
    "import '../providers/delivery_provider.dart';\n\n"
    "class DeliveryScreen extends ConsumerWidget {\n"
    "  const DeliveryScreen({super.key});\n\n"
    "  @override\n"
    "  Widget build(BuildContext context, WidgetRef ref) {\n"
    "    final async = ref.watch(deliveryProvider);\n"
    "    return Scaffold(\n"
    "      backgroundColor: AppColors.background,\n"
    "      appBar: AppBar(backgroundColor: AppColors.surface, elevation: 0,\n"
    "          title: Text('Deliveries', style: AppTextStyles.titleLarge)),\n"
    "      floatingActionButton: FloatingActionButton.extended(\n"
    "        onPressed: () {},\n"
    "        backgroundColor: AppColors.primary,\n"
    "        icon: const Icon(Icons.add_box_rounded, color: Colors.white),\n"
    "        label: Text('Log Delivery', style: AppTextStyles.buttonSmall),\n"
    "      ),\n"
    "      body: async.when(\n"
    "        loading: () => const Center(child: CircularProgressIndicator()),\n"
    "        error: (e, _) => Center(child: Text('Error')),\n"
    "        data: (deliveries) => ListView.builder(\n"
    "          padding: const EdgeInsets.all(16),\n"
    "          itemCount: deliveries.length,\n"
    "          itemBuilder: (ctx, i) {\n"
    "            final d = deliveries[i];\n"
    "            final color = d['status'] == 'pending' ? AppColors.warning\n"
    "                : d['status'] == 'collected' ? AppColors.secondary : AppColors.textMuted;\n"
    "            return Card(\n"
    "              elevation: 0,\n"
    "              margin: const EdgeInsets.only(bottom: 10),\n"
    "              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12),\n"
    "                  side: const BorderSide(color: Color(0xFFE2E8F0))),\n"
    "              child: ListTile(\n"
    "                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),\n"
    "                leading: Container(width: 40, height: 40,\n"
    "                  decoration: BoxDecoration(color: AppColors.info.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),\n"
    "                  child: const Icon(Icons.local_shipping_rounded, color: AppColors.info)),\n"
    "                title: Text('${d[\"courier\"]} to Unit ${d[\"unit\"]}', style: AppTextStyles.body1),\n"
    "                subtitle: Text(d['time'] as String, style: AppTextStyles.bodySmall),\n"
    "                trailing: Container(\n"
    "                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),\n"
    "                  decoration: BoxDecoration(color: color.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(20)),\n"
    "                  child: Text(d['status'] as String, style: AppTextStyles.labelMedium.copyWith(color: color)),\n"
    "                ),\n"
    "              ),\n"
    "            );\n"
    "          },\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

vehicles_screen = (
    "import 'package:flutter/material.dart';\n"
    "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
    "import '../../../core/theme/app_colors.dart';\n"
    "import '../../../core/theme/app_text_styles.dart';\n"
    "import '../providers/vehicles_provider.dart';\n\n"
    "class VehiclesScreen extends ConsumerWidget {\n"
    "  const VehiclesScreen({super.key});\n\n"
    "  @override\n"
    "  Widget build(BuildContext context, WidgetRef ref) {\n"
    "    final async = ref.watch(vehiclesProvider);\n"
    "    return Scaffold(\n"
    "      backgroundColor: AppColors.background,\n"
    "      appBar: AppBar(backgroundColor: AppColors.surface, elevation: 0,\n"
    "          title: Text('Vehicles', style: AppTextStyles.titleLarge),\n"
    "          actions: [IconButton(icon: const Icon(Icons.search_rounded), onPressed: () {})]),\n"
    "      floatingActionButton: FloatingActionButton.extended(\n"
    "        onPressed: () {},\n"
    "        backgroundColor: AppColors.primary,\n"
    "        icon: const Icon(Icons.add_rounded, color: Colors.white),\n"
    "        label: Text('Register Vehicle', style: AppTextStyles.buttonSmall),\n"
    "      ),\n"
    "      body: async.when(\n"
    "        loading: () => const Center(child: CircularProgressIndicator()),\n"
    "        error: (e, _) => Center(child: Text('Error')),\n"
    "        data: (vehicles) => ListView.builder(\n"
    "          padding: const EdgeInsets.all(16),\n"
    "          itemCount: vehicles.length,\n"
    "          itemBuilder: (ctx, i) {\n"
    "            final v = vehicles[i];\n"
    "            final icon = v['type'] == 'car' ? Icons.directions_car_rounded\n"
    "                : v['type'] == 'two_wheeler' ? Icons.two_wheeler_rounded : Icons.pedal_bike_rounded;\n"
    "            return Card(\n"
    "              elevation: 0,\n"
    "              margin: const EdgeInsets.only(bottom: 10),\n"
    "              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12),\n"
    "                  side: const BorderSide(color: Color(0xFFE2E8F0))),\n"
    "              child: ListTile(\n"
    "                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),\n"
    "                leading: Container(width: 40, height: 40,\n"
    "                  decoration: BoxDecoration(color: AppColors.primary.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),\n"
    "                  child: Icon(icon, color: AppColors.primary, size: 20)),\n"
    "                title: Text(v['plate'] as String, style: AppTextStyles.body1),\n"
    "                subtitle: Text('Unit ${v[\"unit\"]} | Slot ${v[\"slot\"]}', style: AppTextStyles.bodySmall),\n"
    "                trailing: const Icon(Icons.chevron_right_rounded, color: AppColors.textMuted),\n"
    "              ),\n"
    "            );\n"
    "          },\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

w(base+'/staff/screens/staff_screen.dart', staff_screen)
w(base+'/gatepasses/screens/gate_pass_screen.dart', gate_pass_screen)
w(base+'/domestichelp/screens/domestic_help_screen.dart', domestic_screen)
w(base+'/deliveries/screens/delivery_screen.dart', delivery_screen)
w(base+'/vehicles/screens/vehicles_screen.dart', vehicles_screen)
print('All 5 screens done')
